receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  file:
    path: /var/log/otel.log

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,file]
