receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:8000

processors:
  batch:

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
